[package]
name = "fusio-manifest"
description = "Backend-agnostic, append-only manifest/WAL for Fusio (RFC-0001)."
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
fusio-core = { path = "../fusio-core", version = "0.4.1", features = ["std"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sha2 = { version = "0.10" }
fusio = { path = "../fusio", version = "0.4.1", default-features = false, features = ["executor", "executor-tokio", "aws", "tokio-http"] }
bytes = { version = "1" }
futures-util = { workspace = true }
futures-channel = "0.3"
futures-executor = { version = "0.3" }
tokio = { version = "1", features = ["sync"] }
async-stream = { version = "0.3" }
backon = "1.4"
thiserror = "2.0.17"
moka = { version = "0.10", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[package.metadata.docs.rs]
all-features = true
